version: '3'

services:
  web:
    container_name: 'web'
    build: ./docker/web
    environment:
      - NODE_ENV=development
    volumes:
      - ./www:/var/www
      - ./docker/web/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - '3000:80'
    tty: true

  db:
    container_name: 'db'
    build: ./docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=docker_pass
    ports:
      - '13306:3306'
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d